import { HomepageSub } from ".";

export default {
  title: "Components/HomepageSub",
  component: HomepageSub,
  argTypes: {
    property1: {
      options: [
        "stand-1",
        "watches-1",
        "laptop-bag-1",
        "preowned-phone-1",
        "variant-6",
        "mic-1",
        "new-phone-1",
        "earphone-1",
        "basic-phone-1",
        "basic-phone-2",
        "no-animation",
        "speakers-2",
        "storage-2",
        "phone-accessory-2",
        "mic-2",
        "keyboard-1",
        "gaming-1",
        "earphone-2",
        "speakers-1",
        "gaming-2",
        "keyboard-2",
        "phone-accessory-1",
        "android-phone-1",
        "new-phone-2",
        "chargers-2",
        "variant-8",
        "pre-owned-phone-2",
        "storage-1",
        "watches-2",
        "iphones-2",
        "androiid-phone-2",
        "stand-2",
        "iphone-1",
        "chargers-1",
        "laptop-bag-2",
        "cases-2",
        "styus-1",
        "cases-1",
        "stylus-2",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    property1: "stand-1",
    className: {},
    groupClassName: {},
    picClassName: {},
    iphoneClassName: {},
    iphone: "/img/iphone-1-54.png",
    img: "/img/iphone-1-53.png",
    iphoneClassNameOverride: {},
    iphone1: "/img/iphone-1-38.png",
    iphone2: "/img/iphone-1-37.png",
    iphone3: "/img/iphone-1-36.png",
    iphone4: "/img/iphone-1-35.png",
    iphone5: "/img/iphone-1-33.png",
    iphone6: "/img/iphone-1-26.png",
    iphone7: "/img/iphone-1-25.png",
  },
};
