import React from "react";
import { BottomDirectory } from "../../components/BottomDirectory";
import { Hero } from "../../components/Hero";
import { HomepageSub } from "../../components/HomepageSub";
import { ProductDisplay } from "../../components/ProductDisplay";
import { PropertyVertical } from "../../components/PropertyVertical";
import { SideBarPhones } from "../../components/SideBarPhones";
import { TopBar } from "../../components/TopBar";
import "./style.css";

export const Catalog = () => {
  return (
    <div className="catalog">
      <div className="div-2">
        <Hero
          biggerHeroPropertyPhonesult="/img/bigger-hero-animation.svg"
          className="hero-instance"
          property1="variant-1"
        />
        <div className="bestsellers">
          <ProductDisplay
            className="product-display-instance"
            divClassName="product-display-3"
            elementStarsImg="/img/star-5-40.svg"
            elementStarsStar="/img/star-4-40.svg"
            elementStarsStar1="/img/star-3-40.svg"
            elementStarsStar2="/img/star-1-40.svg"
            elementStarsStar3="/img/star-2-40.svg"
            image="/img/image-4-32.png"
            imageClassName="product-display-2"
            iphoneProMaxClassName="product-display-3"
            property1="inactive-home-display"
            reviewClassName="product-display-3"
          />
          <ProductDisplay
            className="product-display-4"
            divClassName="product-display-3"
            elementStarsImg="/img/star-5-40.svg"
            elementStarsStar="/img/star-4-40.svg"
            elementStarsStar1="/img/star-3-40.svg"
            elementStarsStar2="/img/star-1-40.svg"
            elementStarsStar3="/img/star-2-40.svg"
            image="/img/image-4-32.png"
            imageClassName="product-display-2"
            iphoneProMaxClassName="product-display-3"
            property1="inactive-home-display"
            reviewClassName="product-display-3"
          />
          <ProductDisplay
            className="frame-28"
            divClassName="product-display-3"
            elementStarsImg="/img/star-5-40.svg"
            elementStarsStar="/img/star-4-40.svg"
            elementStarsStar1="/img/star-3-40.svg"
            elementStarsStar2="/img/star-1-40.svg"
            elementStarsStar3="/img/star-2-40.svg"
            image="/img/image-4-32.png"
            imageClassName="product-display-2"
            iphoneProMaxClassName="product-display-3"
            property1="inactive-home-display"
            reviewClassName="product-display-3"
          />
          <ProductDisplay
            className="frame-29"
            divClassName="product-display-3"
            elementStarsImg="/img/star-5-40.svg"
            elementStarsStar="/img/star-4-40.svg"
            elementStarsStar1="/img/star-3-40.svg"
            elementStarsStar2="/img/star-1-40.svg"
            elementStarsStar3="/img/star-2-40.svg"
            image="/img/image-4-32.png"
            imageClassName="product-display-2"
            iphoneProMaxClassName="product-display-3"
            property1="inactive-home-display"
            reviewClassName="product-display-3"
          />
          <ProductDisplay
            className="frame-30"
            divClassName="product-display-3"
            elementStarsImg="/img/star-5-40.svg"
            elementStarsStar="/img/star-4-40.svg"
            elementStarsStar1="/img/star-3-40.svg"
            elementStarsStar2="/img/star-1-40.svg"
            elementStarsStar3="/img/star-2-40.svg"
            image="/img/image-4-32.png"
            imageClassName="product-display-2"
            iphoneProMaxClassName="product-display-3"
            property1="inactive-home-display"
            reviewClassName="product-display-3"
          />
          <ProductDisplay
            className="frame-31"
            divClassName="product-display-3"
            elementStarsImg="/img/star-5-40.svg"
            elementStarsStar="/img/star-4-40.svg"
            elementStarsStar1="/img/star-3-40.svg"
            elementStarsStar2="/img/star-1-40.svg"
            elementStarsStar3="/img/star-2-40.svg"
            image="/img/image-4-32.png"
            imageClassName="product-display-2"
            iphoneProMaxClassName="product-display-3"
            property1="inactive-home-display"
            reviewClassName="product-display-3"
          />
          <div className="group-10">
            <div className="overlap-group-13">
              <div className="text-wrapper-33">Top Deals</div>
              <div className="see-more">See more &gt;</div>
            </div>
          </div>
        </div>
        <div className="top-deals">
          <ProductDisplay
            className="product-display-5"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-6"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-7"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-8"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-9"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-10"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-11"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            className="product-display-12"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            property1="inactive-catalog-display"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-14"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-19"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-20"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-21"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-22"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-23"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-24"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="product-display-25"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-32"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-33"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-34"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-35"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-36"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-37"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-38"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <ProductDisplay
            buttonsPropertyDefaultClassName="product-display-13"
            className="frame-39"
            divClassName="product-display-17"
            elementStarsImg="/img/star-5-16.svg"
            elementStarsStar="/img/star-4-12.svg"
            elementStarsStar1="/img/star-3-16.svg"
            elementStarsStar2="/img/star-1-12.svg"
            elementStarsStar3="/img/star-2-16.svg"
            imageClassName="product-display-15"
            iphoneProMaxClassName="product-display-16"
            property1="inactive-catalog-display"
            reviewClassName="product-display-18"
          />
          <div className="group-11">
            <div className="frame-40">
              <div className="text-wrapper-34">Mobile Phones</div>
            </div>
            <div className="frame-41">
              <div className="text-wrapper-35">Sort by :</div>
              <PropertyVertical />
            </div>
          </div>
          <div className="group-12">
            <div className="overlap-group-14">
              <div className="frame-42">
                <div className="text-wrapper-36">1-24</div>
                <div className="text-wrapper-37">/</div>
                <div className="text-wrapper-37">240 products found</div>
              </div>
              <div className="see-more-2">See more &gt;</div>
            </div>
          </div>
        </div>
        <BottomDirectory className="bottom-directory-instance" property1="default" />
        <div className="group-13">
          <div className="group-14">
            <div className="overlap-group-15">
              <div className="text-wrapper-33">Quick Links</div>
              <div className="shop-all-phones">Shop all Phones &gt;</div>
            </div>
          </div>
          <HomepageSub
            className="homepage-sub-categories"
            groupClassName="homepage-sub-instance"
            iphone="/img/iphone-1-43.png"
            iphoneClassName="homepage-sub-2"
            picClassName="homepage-sub-categories-instance"
            property1="android-phone-1"
          />
          <HomepageSub
            className="homepage-sub-3"
            groupClassName="homepage-sub-instance"
            img="/img/iphone-1-42.png"
            iphoneClassName="homepage-sub-2"
            picClassName="homepage-sub-categories-instance"
            property1="basic-phone-1"
          />
          <HomepageSub
            className="homepage-sub-4"
            groupClassName="homepage-sub-instance"
            iphone1="/img/iphone-1-41.png"
            iphoneClassName="homepage-sub-2"
            picClassName="homepage-sub-categories-instance"
            property1="new-phone-1"
          />
          <HomepageSub
            className="homepage-sub-5"
            groupClassName="homepage-sub-instance"
            iphone2="/img/iphone-1-40.png"
            iphoneClassName="homepage-sub-2"
            picClassName="homepage-sub-categories-instance"
            property1="preowned-phone-1"
          />
          <HomepageSub
            className="homepage-sub-6"
            groupClassName="homepage-sub-instance"
            iphone3="/img/iphone-1-39.png"
            iphoneClassName="homepage-sub-2"
            picClassName="homepage-sub-categories-instance"
            property1="phone-accessory-1"
          />
          <HomepageSub
            className="homepage-sub-7"
            groupClassName="homepage-sub-8"
            iphone4="/img/iphone-1-38.png"
            iphoneClassName="homepage-sub-2"
            picClassName="homepage-sub-categories-instance"
            property1="iphone-1"
          />
        </div>
        <img className="page-counter" alt="Page counter" src="/img/page-counter.svg" />
        <SideBarPhones
          className="side-bar-phones-instance"
          propertyPriceEllipse="/img/ellipse-23-1.svg"
          ratingSectionPropertyNoStarElementStarsImg="/img/star-2-15.svg"
          ratingSectionPropertyNoStarElementStarsStar="/img/star-5-15.svg"
        />
        <div className="rectangle-4" />
        <TopBar
          className="top-bar-instance"
          frame="/img/frame-40-10.svg"
          img="/img/frame-42-18.svg"
          property1="default"
        />
      </div>
    </div>
  );
};
